var FaceTecStrings = {
  "FaceTec_action_ok": "ОК",
  "FaceTec_action_im_ready": "Я ГОТОВ",
  "FaceTec_action_try_again": "ПОВТОРИТЬ ПОПЫТКУ",
  "FaceTec_action_continue": "ПРОДОЛЖИТЬ",
  "FaceTec_action_take_photo": "СФОТОГРАФИРОВАТЬ",
  "FaceTec_action_accept_photo": "ПРИНЯТЬ",
  "FaceTec_action_retake_photo": "ПОВТ.ФОТО",
  "FaceTec_action_confirm": "ПОДТВЕРДИТЬ ИНФОРМАЦИЮ",

  "FaceTec_accessibility_cancel_button": "Отмена",
  "FaceTec_accessibility_tap_guidance": "Дважды коснитесь любого места на экране для получения рекомендаций по выравниванию лица.",
  "FaceTec_accessibility_key_down_guidance": "Нажмите Enter или пробел, чтобы получить рекомендации по выравниванию лица.",

  "FaceTec_accessibility_feedback_move_phone_away": "Лицо слишком близко",
  "FaceTec_accessibility_feedback_move_phone_closer": "Лицо слишком далеко",
  "FaceTec_accessibility_feedback_face_too_far_left": "Лицо намного левее",
  "FaceTec_accessibility_feedback_face_too_far_right": "Лицо намного правее",
  "FaceTec_accessibility_feedback_face_too_low": "Лицо слишком низко",
  "FaceTec_accessibility_feedback_face_too_high": "Лицо слишком высоко",
  "FaceTec_accessibility_feedback_face_rotated_too_far_left": "Лицо повернуто намного левее",
  "FaceTec_accessibility_feedback_face_rotated_too_far_right": "Лицо повернуто намного правее",
  "FaceTec_accessibility_feedback_face_looking_too_far_left": "Лицо смотрит намного левее",
  "FaceTec_accessibility_feedback_face_looking_too_far_right": "Лицо смотрит намного правее",
  "FaceTec_accessibility_feedback_face_not_in_camera": "Лицо не в камере",
  "FaceTec_accessibility_feedback_hold_phone_to_eye_level": "Держите устройство на уровне глаз",
  "FaceTec_accessibility_feedback_move_away_web": "Камера слишком близко",
  "FaceTec_accessibility_feedback_move_closer_web": "Камера слишком далеко",
  "FaceTec_accessibility_feedback_hold_to_eye_level_web": "Переместите камеру на уровень глаз",

  "FaceTec_presession_frame_your_face": "Поместите свое лицо в овал",
  "FaceTec_presession_look_straight_ahead": "Смотрите прямо перед собой",
  "FaceTec_presession_hold_steady3": "Не двигайтесь: 3",
  "FaceTec_presession_hold_steady2": "Не двигайтесь: 2",
  "FaceTec_presession_hold_steady1": "Не двигайтесь: 1",
  "FaceTec_presession_eyes_straight_ahead": "Смотрите прямо перед собой",
  "FaceTec_presession_remove_dark_glasses": "Снимите темные очки",
  "FaceTec_presession_neutral_expression": "Нейтральное выражение лица, без улыбки",
  "FaceTec_presession_conditions_too_bright": "Слишком яркая обстановка",
  "FaceTec_presession_brighten_your_environment": "Сделайте свою обстановку ярче",

  "FaceTec_feedback_center_face": "Поместите свое лицо в центр",
  "FaceTec_feedback_face_not_found": "Поместите свое лицо в рамку",
  "FaceTec_feedback_move_phone_away": "Отодвиньтесь дальше",
  "FaceTec_feedback_move_away_web": "Отодвиньтесь дальше",
  "FaceTec_feedback_move_phone_closer": "Придвиньтесь ближе",
  "FaceTec_feedback_move_web_closer": "Приблизьте лицо и заполните овал",
  "FaceTec_feedback_move_web_even_closer": "Еще Ближе",
  "FaceTec_feedback_move_phone_to_eye_level": "Держите камеру на уровне глаз",
  "FaceTec_feedback_move_to_eye_level_web": "Смотрите Прямо В Камеру",
  "FaceTec_feedback_face_not_looking_straight_ahead": "Смотрите прямо перед собой",
  "FaceTec_feedback_face_not_upright": "Держите голову прямо",
  "FaceTec_feedback_face_not_upright_mobile": "Держите голову прямо",
  "FaceTec_feedback_hold_steady": "Не двигайтесь",
  "FaceTec_feedback_use_even_lighting": "Осветите лицо более равномерно",

  "FaceTec_instructions_header_ready_desktop": "Приготовьтесь к вашему видеоселфи",
  "FaceTec_instructions_header_ready_1_mobile": "Приготовьтесь к",
  "FaceTec_instructions_header_ready_2_mobile": "вашему видеоселфи",
  "FaceTec_instructions_message_ready_desktop": "Поместите свое лицо в овал, Нажмите \"Я готов\" и придвиньтесь ближе",
  "FaceTec_instructions_message_ready_1_mobile": "Поместите свое лицо в овал",
  "FaceTec_instructions_message_ready_2_mobile": "Нажмите \"Я готов\" и придвиньтесь ближе",

  "FaceTec_retry_header": "Давайте попробуем еще раз",
  "FaceTec_retry_subheader_message": "Нам нужно более четкое видеоселфи",
  "FaceTec_retry_your_image_label": "Ваше селфи",
  "FaceTec_retry_ideal_image_label": "Идеальная поза",
  "FaceTec_retry_instruction_message_1": "Отсутствие бликов или сильного освещения",
  "FaceTec_retry_instruction_message_2": "Нейтральное выражение лица, без улыбки",
  "FaceTec_retry_instruction_message_3": "Слишком размыто, почистите камеру",

  "FaceTec_camera_feed_issue_header": "Проблема, защищая подключение к камере",
  "FaceTec_camera_feed_issue_header_mobile": "Проблема для защиты <br/>подключение к камере",
  "FaceTec_camera_feed_issue_subheader_message_mobile": "Это приложение блокирует подозрительные веб -конфигурации. <br/><a href='https://livenesscheckhelp.com/' target='_blank' style='text-decoration:underline; pointer-events:all;'>Узнайте больше здесь.</a>.",
  "FaceTec_camera_feed_issue_subheader_message": "Эта система не может быть проверена из -за следующего:",
  "FaceTec_camera_feed_issue_table_header_1": "Возможная проблема",
  "FaceTec_camera_feed_issue_table_header_2": "Правильный",
  "FaceTec_camera_feed_issue_table_row_1_cell_1_firefox_permissions_error": "Палата разрешений не помнят в Firefox.",
  "FaceTec_camera_feed_issue_table_row_1_cell_2_firefox_permissions_error": "Марк помните разрешения.",
  "FaceTec_camera_feed_issue_table_row_1_cell_1": "Палата уже используется другим приложением.",
  "FaceTec_camera_feed_issue_table_row_1_cell_2": "Закрыть другое приложение.",
  "FaceTec_camera_feed_issue_table_row_2_cell_1": "Приложение 3-го парка модифицирует видео.",
  "FaceTec_camera_feed_issue_table_row_2_cell_2": "Закрыть / удалить другое приложение.",
  "FaceTec_camera_feed_issue_table_row_3_cell_1": "Оборудование, которое не может быть защищено.",
  "FaceTec_camera_feed_issue_table_row_3_cell_2": "Используйте другое устройство.",
  "FaceTec_camera_feed_issue_subtable_message": "Это приложение блокирует подозрительные веб -конфигурации. <a href='https://livenesscheckhelp.com/' target='_blank' style='text-decoration:underline; pointer-events:all;'>Узнайте больше здесь.</a>.",
  "FaceTec_camera_feed_issue_action": "ПОВТОРИТЬ ПОПЫТКУ",
  "FaceTec_camera_feed_issue_action_firefox_permissions_error": "ОК",

  "FaceTec_camera_permission_header": "Включить камеру",
  "FaceTec_camera_permission_message": "Разрешения для камеры отключены.<br/>пожалуйста, проверьте настройки вашей операционной системы и браузера",

  "FaceTec_enter_fullscreen_header": "Полноэкранный режим селфи",
  "FaceTec_enter_fullscreen_message": "Прежде чем мы начнем, пожалуйста, нажмите на кнопку ниже, чтобы открыть полноэкранный режим.",
  "FaceTec_enter_fullscreen_action": "ОТКРЫТЬ НА ВЕСЬ ЭКРАН",

  "FaceTec_initializing_camera": "Защита данных с камеры",

  "FaceTec_idscan_type_selection_header": "Подготовьтесь к сканированию<br/>вашего идентификационного документа",
  "FaceTec_idscan_capture_id_front_instruction_message": "Покаж.передн.стор.идент.докум.",
  "FaceTec_idscan_capture_id_back_instruction_message": "Покаж.обратн.стор.идент.докум.",
  "FaceTec_idscan_review_id_front_instruction_message": "Подтвердите, что фотогр.четкая",
  "FaceTec_idscan_review_id_back_instruction_message": "Подтвердите, что фотогр.четкая",
  "FaceTec_idscan_additional_review_message": "Требуется дополнительная<br/>проверка",
  "FaceTec_idscan_ocr_confirmation_main_header": "Проверьте и подтвердите",
  "FaceTec_idscan_ocr_confirmation_scroll_message": "Прокрутите вниз",
  "FaceTec_idscan_feedback_flip_id_to_back_message": "Покаж.обратн.стор.идент.докум.",

  "FaceTec_result_success_message": "Успешно",
  "FaceTec_result_facescan_upload_message": "Загрузка<br/>зашифрованного<br/>3D-скана лица",
  "FaceTec_result_idscan_upload_message": "Загрузка<br/>зашифрованного<br/>скана идентификационного документа",
  "FaceTec_result_idscan_unsuccess_message": "Фото на идентификационном документе<br/>не соответствует<br/>лицу пользователя",
  "FaceTec_result_idscan_success_front_side_message": "Сканирование идентификационного документа завершено",
  "FaceTec_result_idscan_success_front_side_back_next_message": "Передняя сторона идентификационного документа<br/>отсканирована",
  "FaceTec_result_idscan_success_back_side_message": "Сканирование идентификационного документа завершено",
  "FaceTec_result_idscan_success_passport_message": "Сканирование паспорта завершено",
  "FaceTec_result_idscan_success_user_confirmation_message": "Сканирование идентификационного документа с фотографией<br/>завершено",
  "FaceTec_result_idscan_success_additional_review_message": "Фотосъемка идентификационного документа<br/>завершена",
  "FaceTec_result_idscan_retry_face_did_not_match_message": "Лицо не соответствует<br/>достаточно сильно",
  "FaceTec_result_idscan_retry_id_not_fully_visible_message": "Идентификационный документ<br/>виден не полностью",
  "FaceTec_result_idscan_retry_ocr_results_not_good_enough_message": "Текст на идентификационном документе не разборчив",
  "FaceTec_result_idscan_retry_id_type_not_suppported_message": "Тип идентификационного документа не поддерживается,<br/>пожалуйста, используйте другой идентификационный документ",
  "FaceTec_result_idscan_retry_barcode_not_read_message": "Не удалось отсканировать штрих-код,<br/>пожалуйста, попробуйте еще раз",
};

module.exports = FaceTecStrings;
