var FaceTecStrings = {
  "FaceTec_action_ok": "OK",
  "FaceTec_action_im_ready": "JEG ER KLAR",
  "FaceTec_action_try_again": "PRØV IGJEN",
  "FaceTec_action_continue": "FORTSETT",
  "FaceTec_action_take_photo": "TA BILDE",
  "FaceTec_action_accept_photo": "AKSEPTER",
  "FaceTec_action_retake_photo": "TA NYTT",
  "FaceTec_action_confirm": "BEKREFT INFO",

  "FaceTec_accessibility_cancel_button": "Kanseller",
  "FaceTec_accessibility_tap_guidance": "Dobbeltrykk hvor som helst på skjermen for veiledning om justering av ansiktsplasseringen.",
  "FaceTec_accessibility_key_down_guidance": "Trykk på Enter eller mellomromstasten for veiledning for ansiktsjustering",

  "FaceTec_accessibility_feedback_move_phone_away": "Ansikt for nærme",
  "FaceTec_accessibility_feedback_move_phone_closer": "Ansikt for langt vekke",
  "FaceTec_accessibility_feedback_face_too_far_left": "Ansikt for langt til venstre",
  "FaceTec_accessibility_feedback_face_too_far_right": "Ansikt for langt til høyre",
  "FaceTec_accessibility_feedback_face_too_low": "Ansikt for lavt",
  "FaceTec_accessibility_feedback_face_too_high": "Ansikt for høyt",
  "FaceTec_accessibility_feedback_face_rotated_too_far_left": "Ansikt rotert for langt til venstre",
  "FaceTec_accessibility_feedback_face_rotated_too_far_right": "Ansikt rotert for langt til høyre",
  "FaceTec_accessibility_feedback_face_looking_too_far_left": "Ansikt peker for langt til venstre",
  "FaceTec_accessibility_feedback_face_looking_too_far_right": "Ansikt peker for langt til høyre",
  "FaceTec_accessibility_feedback_face_not_in_camera": "Ansikt ikke på kameraet",
  "FaceTec_accessibility_feedback_hold_phone_to_eye_level": "Hold enheten i øyehøyde",
  "FaceTec_accessibility_feedback_move_away_web": "Kameraet er for nært",
  "FaceTec_accessibility_feedback_move_closer_web": "Kameraet er for langt unna",
  "FaceTec_accessibility_feedback_hold_to_eye_level_web": "Flytt kamera til øyehøyde",

  "FaceTec_presession_frame_your_face": "Ram ansiktet ditt inn i ovalen",
  "FaceTec_presession_look_straight_ahead": "Se rett fremover",
  "FaceTec_presession_hold_steady3": "Hold i ro i: 3",
  "FaceTec_presession_hold_steady2": "Hold i ro i: 2",
  "FaceTec_presession_hold_steady1": "Hold i ro i: 1",
  "FaceTec_presession_eyes_straight_ahead": "Se rett fremover",
  "FaceTec_presession_remove_dark_glasses": "Ta av mørke briller",
  "FaceTec_presession_neutral_expression": "Naturlig uttrykk, ingen smiling",
  "FaceTec_presession_conditions_too_bright": "For lyse forhold",
  "FaceTec_presession_brighten_your_environment": "Gjør miljøet lysere",

  "FaceTec_feedback_center_face": "Sentrer ansiktet ditt",
  "FaceTec_feedback_face_not_found": "Ram inn ansiktet ditt",
  "FaceTec_feedback_move_phone_away": "Flytt deg lengre fra",
  "FaceTec_feedback_move_away_web": "Flytt deg lengre fra",
  "FaceTec_feedback_move_phone_closer": "Flytt deg nærmere",
  "FaceTec_feedback_move_web_closer": "Ta ansiktet nærmere og fyll ut det ovale",
  "FaceTec_feedback_move_web_even_closer": "Enda nærmere",
  "FaceTec_feedback_move_phone_to_eye_level": "Flytt kameraet til øyenivå",
  "FaceTec_feedback_move_to_eye_level_web": "Se direkte på kameraet",
  "FaceTec_feedback_face_not_looking_straight_ahead": "Se rett fremover",
  "FaceTec_feedback_face_not_upright": "Hold hodet rett",
  "FaceTec_feedback_face_not_upright_mobile": "Hold hodet rett",
  "FaceTec_feedback_hold_steady": "Hold i ro",
  "FaceTec_feedback_use_even_lighting": "Anvend jevnere lys på ansiktet",

  "FaceTec_instructions_header_ready_desktop": "Gjør deg klar til Video-selfien din",
  "FaceTec_instructions_header_ready_1_mobile": "Gjør deg klar til",
  "FaceTec_instructions_header_ready_2_mobile": "Video-selfien din",
  "FaceTec_instructions_message_ready_desktop": "Ram ansiktet ditt inn i ovalen, Trykk på «Jeg er klar» og kom nærmere",
  "FaceTec_instructions_message_ready_1_mobile": "Ram ansiktet ditt inn i ovalen",
  "FaceTec_instructions_message_ready_2_mobile": "Trykk på «Jeg er klar» og kom nærmere",

  "FaceTec_retry_header": "La oss prøve det igjen",
  "FaceTec_retry_subheader_message": "Vi trenger en klarere video-selfie",
  "FaceTec_retry_your_image_label": "Selfien din",
  "FaceTec_retry_ideal_image_label": "Ideell posering",
  "FaceTec_retry_instruction_message_1": "Ingen kraftig skinn eller sterkt lys",
  "FaceTec_retry_instruction_message_2": "Naturlig uttrykk, ingen smiling",
  "FaceTec_retry_instruction_message_3": "For uklart, rens kameraet",

  "FaceTec_camera_feed_issue_header": "Problem ved å beskytte kameraforbindelsen",
  "FaceTec_camera_feed_issue_header_mobile": "Problem å beskytte <br/>kammerforbindelsen",
  "FaceTec_camera_feed_issue_subheader_message_mobile": "Denne applikasjonen blokkerer mistenkelige nettkonfigurasjoner.<br/><a href='https://livenesscheckhelp.com/' target='_blank' style='text-decoration:underline; pointer-events:all;'>Lær mer her.</a>.",
  "FaceTec_camera_feed_issue_subheader_message": "Dette systemet kan ikke bekreftes på grunn av følgende:",
  "FaceTec_camera_feed_issue_table_header_1": "Mulig problem",
  "FaceTec_camera_feed_issue_table_header_2": "Riktig",
  "FaceTec_camera_feed_issue_table_row_1_cell_1_firefox_permissions_error": "Kammer tillater ikke husket i Firefox.",
  "FaceTec_camera_feed_issue_table_row_1_cell_2_firefox_permissions_error": "Mark husker tillatelser.",
  "FaceTec_camera_feed_issue_table_row_1_cell_1": "Kammer som allerede er i bruk av en annen applikasjon.",
  "FaceTec_camera_feed_issue_table_row_1_cell_2": "Lukk den andre applikasjonen.",
  "FaceTec_camera_feed_issue_table_row_2_cell_1": "En tredje-park-applikasjon endrer videoen.",
  "FaceTec_camera_feed_issue_table_row_2_cell_2": "Lukk / avinstaller den andre applikasjonen.",
  "FaceTec_camera_feed_issue_table_row_3_cell_1": "Utstyr som ikke kan beskyttes.",
  "FaceTec_camera_feed_issue_table_row_3_cell_2": "Bruk en annen enhet.",
  "FaceTec_camera_feed_issue_subtable_message": "Denne applikasjonen blokkerer mistenkelige nettkonfigurasjoner. <a href='https://livenesscheckhelp.com/' target='_blank' style='text-decoration:underline; pointer-events:all;'>Lær mer her.</a>.",
  "FaceTec_camera_feed_issue_action": "PRØV IGJEN",
  "FaceTec_camera_feed_issue_action_firefox_permissions_error": "OK",

  "FaceTec_camera_permission_header": "Aktiver kameraet",
  "FaceTec_camera_permission_message": "Kamera tillatelser deaktivert.<br/>kontroller innstillingene for operativsystemet og nettleseren",

  "FaceTec_enter_fullscreen_header": "Selfie-Modus På Full Skjerm",
  "FaceTec_enter_fullscreen_message": "Før vi begynner, vennligst klikk på knappen nedenfor for å åpne fullskjermmodus.",
  "FaceTec_enter_fullscreen_action": "ÅPNE I FULL SKJERM",

  "FaceTec_initializing_camera": "Sikrer kamera-feeden",

  "FaceTec_idscan_type_selection_header": "Gjør klar til å skanne<br/>ID-dokumentet ditt",
  "FaceTec_idscan_capture_id_front_instruction_message": "Vis ID-ens forside",
  "FaceTec_idscan_capture_id_back_instruction_message": "Vis ID-ens bakside",
  "FaceTec_idscan_review_id_front_instruction_message": "Bekreft at foto er klart/lesbart",
  "FaceTec_idscan_review_id_back_instruction_message": "Bekreft at foto er klart/lesbart",
  "FaceTec_idscan_additional_review_message": "Ekstra gjennomgang<br/>påkrevd",
  "FaceTec_idscan_ocr_confirmation_main_header": "Gjennomgå og bekreft",
  "FaceTec_idscan_ocr_confirmation_scroll_message": "Skroll ned",

  "FaceTec_result_success_message": "Vellykket",
  "FaceTec_result_facescan_upload_message": "Laster opp<br/>kryptert<br/>3D-ansiktsskanning",
  "FaceTec_result_idscan_upload_message": "Laster opp<br/>kryptert<br/>ID-skanning",
  "FaceTec_result_idscan_unsuccess_message": "ID-foto<br/>matchet ikke<br/>brukerens ansikt",
  "FaceTec_result_idscan_success_front_side_message": "ID-skanning fullført",
  "FaceTec_result_idscan_success_front_side_back_next_message": "ID-ens forside<br/>skannet",
  "FaceTec_result_idscan_success_back_side_message": "ID-skanning fullført",
  "FaceTec_result_idscan_success_passport_message": "Pass-skanning fullført",
  "FaceTec_result_idscan_success_user_confirmation_message": "Foto-ID-skanning<br/>fullført",
  "FaceTec_result_idscan_success_additional_review_message": "ID-fotofangst<br/>fullført",
  "FaceTec_result_idscan_retry_face_did_not_match_message": "Ansiktet matchet ikke<br/>godt nok",
  "FaceTec_result_idscan_retry_id_not_fully_visible_message": "ID-dokument<br/>ikke helt synlig",
  "FaceTec_result_idscan_retry_ocr_results_not_good_enough_message": "ID-tekst ikke lesbar",
  "FaceTec_result_idscan_retry_id_type_not_suppported_message": "ID-type ikke støttet<br/>bruk en annen ID",
  "FaceTec_result_idscan_retry_barcode_not_read_message": "Kunne ikke skanne strekkode<br/>prøv igjen",
};

module.exports = FaceTecStrings;
